### ISSUE TITLE
Missing master.php?

### ISSUE THREAD

**Issue by pascal-linux** [lonnieezell/BonfireNext#1]
Hi,
I really like Codeigniter and want to migrate from my current CI3 application to CI4.
And bonfire looks really interesting!

I installed it but got an error (in production environment) - saying that the view/file master.php is missing. Is this something I have to configure - or should these view files be part of bonfire / CI4?
I did not find them ...
Error-Message
> CodeIgniter\View\Exceptions\ViewException
Invalid file: master.php
SYSTEMPATH/Exceptions\FrameworkException.php at line 17
 class FrameworkException extends \RuntimeException implements ExceptionInterface
 {
     public static function forInvalidFile(string $path)
     {
        return new static(lang('Core.invalidFile', [$path]));
..

Top of welcome.php:

```
<?php $this->extend('master') ?>
<?php $this->section('content') ?>
<div class="container">
..
```

Thanks,
PAscal

**Comment by lonnieezell** [comment]
This project is in the very earliest stages of getting started again. So it won't work.
