### ISSUE TITLE
Will the project come to life just like the previous version?

### ISSUE THREAD

**Issue by colonelo** [lonnieezell/BonfireNext#2]
Hi Lonnie.

I can see that there are new versions (Bootstrap , CI, Jquery) in the background of the prepared project. What is planned in the future ? Will the project come to life just like the previous version?
I have used the previous version in production and I am very pleased...

Regards,

Matej
Slovenia, EU

**Comment by lonnieezell** [comment]
Honestly - I'm undecided on its future at this point. I had planned on building out a new version with some new features, but not sure I really have the time to support this. That doesn't mean I won't pick it back up, but right now there's nothing in stone either way.
